In [1]:
import numpy as np 
import pandas as pd

In [3]:
A = np.array([1, 2, 3, 0])
A.argsort()

array([3, 0, 1, 2], dtype=int64)

In [4]:
A[::-1]

array([0, 3, 2, 1])

In [10]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.mean(A, axis=1)

array([2., 5., 8.])

In [ ]:
class PCA: 
    def __init__(self, n_dimension: int):
        self.n_dimension = n_dimension

    def fit_transform(self, X):
        mean = np.mean(axis=0)
        X_center = X - mean
        X_cov = (1 / X.shape[0]) * (X_center @ X_center.T)
        eigen_values, eigen_vectors = np.linalg.eig(X_cov)
        select_index = np.argsort(eigen_values)[::-1][:self.n_dimension]
        