In [1]:
import numpy as np

In [2]:
p = np.array((0.3, 0.333, 0.287, 0.08))

In [3]:
p.sum(axis=0)

0.9999999999999999

In [4]:
cov_matrix = np.diag(p) - p.reshape(p.shape[0], 1) @ p.reshape(1, p.shape[0])
cov_matrix

array([[ 0.21    , -0.0999  , -0.0861  , -0.024   ],
       [-0.0999  ,  0.222111, -0.095571, -0.02664 ],
       [-0.0861  , -0.095571,  0.204631, -0.02296 ],
       [-0.024   , -0.02664 , -0.02296 ,  0.0736  ]])

In [5]:
cov_matrix.sum(axis=0)

array([-6.93889390e-18, -3.46944695e-18,  1.04083409e-17,  0.00000000e+00])

In [6]:
cov_matrix.sum(axis=1)

array([-6.93889390e-18, -3.46944695e-18,  1.04083409e-17,  0.00000000e+00])

In [7]:
A = np.array([[0, 1], [0, 1], [1, 0], [0, 1], [1, 0]])
centered_A = A - np.mean(A, axis=0)
centered_A

array([[-0.4,  0.4],
       [-0.4,  0.4],
       [ 0.6, -0.6],
       [-0.4,  0.4],
       [ 0.6, -0.6]])

In [8]:
cov_matrix_A = centered_A.T @ centered_A / centered_A.shape[0]
cov_matrix_A

array([[ 0.24, -0.24],
       [-0.24,  0.24]])

In [9]:
p = np.array([0.4, 0.6])
p

array([0.4, 0.6])

In [10]:
cov_matrix = np.diag(p) - p.reshape((p.shape[0], 1)) @ p.reshape((1, p.shape[0]))
cov_matrix

array([[ 0.24, -0.24],
       [-0.24,  0.24]])

In [11]:
data = np.array([[7, 33, 5], [24, 18, 8], [13, 30, 0], [3, 7, 2]])
data

array([[ 7, 33,  5],
       [24, 18,  8],
       [13, 30,  0],
       [ 3,  7,  2]])

In [12]:
A = data.sum(axis=1)
A

array([45, 50, 43, 12])

In [14]:
prob_row = A / A.sum()
prob_row

array([0.3       , 0.33333333, 0.28666667, 0.08      ])

In [15]:
p1 = np.array([0.3, 0.333, 0.287, 0.08])
p1

array([0.3  , 0.333, 0.287, 0.08 ])

In [16]:
p2 = np.array([0.313, 0.587, 0.1])
p2

array([0.313, 0.587, 0.1  ])

In [18]:
cov_11 = np.diag(p1) - p1.reshape((p1.shape[0], 1)) * p1.reshape((1, p1.shape[0]))
cov_11

array([[ 0.21    , -0.0999  , -0.0861  , -0.024   ],
       [-0.0999  ,  0.222111, -0.095571, -0.02664 ],
       [-0.0861  , -0.095571,  0.204631, -0.02296 ],
       [-0.024   , -0.02664 , -0.02296 ,  0.0736  ]])

In [25]:
cov_22 = np.diag(p2) - p2.reshape((p2.shape[0], 1)) @ p2.reshape((1, p2.shape[0]))
cov_22

array([[ 0.215031, -0.183731, -0.0313  ],
       [-0.183731,  0.242431, -0.0587  ],
       [-0.0313  , -0.0587  ,  0.09    ]])

In [26]:
data.sum()

150

In [27]:
joint_prob = data / data.sum()
joint_prob

array([[0.04666667, 0.22      , 0.03333333],
       [0.16      , 0.12      , 0.05333333],
       [0.08666667, 0.2       , 0.        ],
       [0.02      , 0.04666667, 0.01333333]])

In [28]:
print(p1)
print(p2)

[0.3   0.333 0.287 0.08 ]
[0.313 0.587 0.1  ]


In [30]:
cov_12 = (data / data.sum()) - p1.reshape((p1.shape[0], 1)) @ p2.reshape((1, p2.shape[0]))
cov_12

array([[-0.04723333,  0.0439    ,  0.00333333],
       [ 0.055771  , -0.075471  ,  0.02003333],
       [-0.00316433,  0.031531  , -0.0287    ],
       [-0.00504   , -0.00029333,  0.00533333]])

In [32]:
cov = np.block([[cov_11, cov_12], [cov_12.T, cov_22]])
cov

array([[ 0.21      , -0.0999    , -0.0861    , -0.024     , -0.04723333,
         0.0439    ,  0.00333333],
       [-0.0999    ,  0.222111  , -0.095571  , -0.02664   ,  0.055771  ,
        -0.075471  ,  0.02003333],
       [-0.0861    , -0.095571  ,  0.204631  , -0.02296   , -0.00316433,
         0.031531  , -0.0287    ],
       [-0.024     , -0.02664   , -0.02296   ,  0.0736    , -0.00504   ,
        -0.00029333,  0.00533333],
       [-0.04723333,  0.055771  , -0.00316433, -0.00504   ,  0.215031  ,
        -0.183731  , -0.0313    ],
       [ 0.0439    , -0.075471  ,  0.031531  , -0.00029333, -0.183731  ,
         0.242431  , -0.0587    ],
       [ 0.00333333,  0.02003333, -0.0287    ,  0.00533333, -0.0313    ,
        -0.0587    ,  0.09      ]])

In [33]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.sum(axis=0)

array([5, 7, 9])